# Development python environment
name: pivuq
dependencies:
  - pip
  - python=3.9
  - pip:
    - ipython
    - jupyterlab
    - matplotlib
    - poetry
    - pre-commit
    - pytest
    - -r docs/requirements.txt # documentation
