# Development python environment
channels:
  - conda-forge
name: pivuq
dependencies:
  - pip
  - python=3.9
  - pip:
    - ipython
    - poetry
    - -r docs/requirements.txt # documentation and examples
